/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gateway.view.Login;

import gateway.controllers.AdministratorController;
import gateway.controllers.UserAccountController;
import gateway.view.home.Home;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pesshala
 */
public class CreataeNewUserAccount extends javax.swing.JPanel {

    /**
     * Creates new form CretaeNewUserAccount
     */
    CreataeNewUserAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtAdminPassword = new javax.swing.JPasswordField();
        jPanel20 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel51 = new javax.swing.JLabel();
        txtConfirmPassword6 = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        labelMatch2 = new javax.swing.JLabel();
        labelStrength2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Admin Permission");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 82, 14));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 51));
        jLabel6.setText("Admin Permission :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtAdminPassword.setOpaque(false);
        jPanel1.add(txtAdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 240, 30));

        panel.add(jPanel1);
        jPanel1.setBounds(0, 390, 430, 72);

        jPanel20.setOpaque(false);
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setText("Set Password");
        jPanel20.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel50.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 153, 51));
        jLabel50.setText("Password                :");
        jPanel20.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel20.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 73, 10));

        jLabel51.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 153, 51));
        jLabel51.setText("Confirm Password :");
        jPanel20.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtConfirmPassword6.setOpaque(false);
        txtConfirmPassword6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfirmPassword6KeyReleased(evt);
            }
        });
        jPanel20.add(txtConfirmPassword6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 230, 30));

        txtPassword.setOpaque(false);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        jPanel20.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 240, 30));

        labelMatch2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel20.add(labelMatch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 126, 100, 15));
        jPanel20.add(labelStrength2, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 44, 98, 15));

        panel.add(jPanel20);
        jPanel20.setBounds(10, 240, 530, 141);

        txtName.setOpaque(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        panel.add(txtName);
        txtName.setBounds(190, 120, 240, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("Employer Name      :");
        panel.add(jLabel2);
        jLabel2.setBounds(20, 130, 160, 22);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 102));
        jLabel7.setText("Prefered User Name:");
        panel.add(jLabel7);
        jLabel7.setBounds(10, 190, 160, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("    EXIT");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        panel.add(jLabel5);
        jLabel5.setBounds(570, 60, 61, 22);

        txtUserName.setOpaque(false);
        panel.add(txtUserName);
        txtUserName.setBounds(190, 190, 240, 30);

        jLabel3.setText("         Save");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        panel.add(jLabel3);
        jLabel3.setBounds(520, 434, 90, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 204, 255));
        jLabel8.setText("Create New User Account");
        panel.add(jLabel8);
        jLabel8.setBounds(10, 50, 310, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gateway/view/images/home/CreateUserAccount.png"))); // NOI18N
        panel.add(jLabel1);
        jLabel1.setBounds(0, -6, 648, 500);

        add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 500));
    }// </editor-fold>//GEN-END:initComponents
    private boolean AdminPass() {
        boolean permision = false;
        try {
            String password = txtAdminPassword.getText();
            permision = AdministratorController.getAdminPassword(password);
        } catch (SQLException ex) {
            Logger.getLogger(CreataeNewUserAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CreataeNewUserAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
        return permision;
    }
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (AdminPass()) {
            if ("matched".equals(labelMatch2.getText())) {
                try {
                    String name = txtName.getText();
                    String userName = txtUserName.getText();
                    String password = txtPassword.getText();
                    gateway.model.UserAccount userAccount = new gateway.model.UserAccount(name, userName, password);
                    int res = UserAccountController.addUserAccount(userAccount);
                    if (res > 0) {
                        Object[] options = {"Login from this account", "Login from other account"};
                        int response = JOptionPane.showOptionDialog(null, "User-Account created succesfully. select mode of login ", "Login Mode", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
                        if (response == 0) {
                            Home home= new  Home();
                            home.setVisible(true);
                        }else{
                            UserAccount account=new UserAccount();
                            account.setSize(panel.getSize());
                            panel.removeAll();
                            panel.add(account);
                            panel.repaint();
                            panel.revalidate();
                        }
                    }
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(CreataeNewUserAccount.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Passwords you entered do not match  !!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Admin permision denied  ");
        }


    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtConfirmPassword6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmPassword6KeyReleased

        char[] password = txtPassword.getPassword();
        char[] confirmpassword = txtConfirmPassword6.getPassword();
        String match = "";
        if (confirmpassword.length <= password.length) {
            for (int i = 0; i < confirmpassword.length; i++) {
                if (match == "" || match == "matched") {
                    if (password[i] == confirmpassword[i]) {
                        match = "matched";
                        //                    match="matched";
                        //                    labelMatch.setText(match);
                    } else {
                        match = "mis-match";

                    }
                } else {

                }
            }
            //        if(password.length==confirmpassword.length){
            //            labelMatch.setText(match);
            //        }
        } else if (confirmpassword.length > password.length) {
            match = "longer than password";
        }
        if (confirmpassword.length == 0) {
            labelMatch2.setText("");
        } else if (password.length == confirmpassword.length) {
            labelMatch2.setText(match);
        } else if (password.length > confirmpassword.length) {
            if (match == "mis-match") {
                labelMatch2.setText(match);
            } else {
                labelMatch2.setText("");
            }
        } else if (password.length < confirmpassword.length) {
            labelMatch2.setText(match);
        }
        //        System.out.println(password);
        //        String confirmpassword=txtConfirmPassword.getPassword().toString();
        //        System.out.println(confirmpassword);
    }//GEN-LAST:event_txtConfirmPassword6KeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        //        String password=txtPassword.getSelectedText()
        //
        //                look bellow

        // methanamama ganna one count elkanam nmka hadathki matma
        //eth methan password eke akuruwalata ints letters adanguda kyala balnnannam aniwa me Strings split kranna ona
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(1);
    }//GEN-LAST:event_jLabel5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel labelMatch2;
    private javax.swing.JLabel labelStrength2;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField txtAdminPassword;
    private javax.swing.JPasswordField txtConfirmPassword6;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
