/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gateway.view.Login;

import gateway.controllers.AdministratorController;
import static gateway.libraries.CurInstance.Date;
import gateway.model.AdminAccount;
import gateway.view.home.Home;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pesshala
 */
public class NewAdminAccount extends javax.swing.JPanel {

    /**
     * Creates new form NewAdminAccount
     */
    public NewAdminAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel51 = new javax.swing.JLabel();
        txtConfirmPassword6 = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        labelMatch2 = new javax.swing.JLabel();
        labelStrength2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        loadPanel.setOpaque(false);
        loadPanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("Prefered User Name:");
        loadPanel.add(jLabel2);
        jLabel2.setBounds(20, 200, 160, 22);

        txtUserName.setOpaque(false);
        loadPanel.add(txtUserName);
        txtUserName.setBounds(180, 200, 244, 30);

        jPanel20.setOpaque(false);
        jPanel20.setLayout(null);

        jLabel49.setText("Set Password");
        jPanel20.add(jLabel49);
        jLabel49.setBounds(10, 10, 65, 14);

        jLabel50.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 153, 51));
        jLabel50.setText("Password                :");
        jPanel20.add(jLabel50);
        jLabel50.setBounds(20, 50, 158, 22);
        jPanel20.add(jSeparator12);
        jSeparator12.setBounds(10, 30, 73, 10);

        jLabel51.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 153, 51));
        jLabel51.setText("Confirm Password :");
        jPanel20.add(jLabel51);
        jLabel51.setBounds(20, 100, 154, 22);

        txtConfirmPassword6.setOpaque(false);
        txtConfirmPassword6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfirmPassword6KeyReleased(evt);
            }
        });
        jPanel20.add(txtConfirmPassword6);
        txtConfirmPassword6.setBounds(180, 110, 245, 32);

        txtPassword.setOpaque(false);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        jPanel20.add(txtPassword);
        txtPassword.setBounds(180, 50, 243, 37);

        labelMatch2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel20.add(labelMatch2);
        labelMatch2.setBounds(430, 126, 100, 15);
        jPanel20.add(labelStrength2);
        labelStrength2.setBounds(412, 44, 98, 15);

        loadPanel.add(jPanel20);
        jPanel20.setBounds(0, 265, 550, 180);

        jLabel3.setText("     Save");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        loadPanel.add(jLabel3);
        jLabel3.setBounds(510, 440, 100, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("EXIT");
        loadPanel.add(jLabel4);
        jLabel4.setBounds(584, 70, 60, 30);

        add(loadPanel);
        loadPanel.setBounds(3, -4, 640, 510);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gateway/view/images/home/CreateNewAdmin.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 504);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (!"".equals(txtUserName.getText())) {
            if ("matched".equals(labelMatch2.getText())) {
                try {
                    SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
                    String date = sdf.format(new Date());
                    String userName = txtUserName.getText();
                    String password = txtPassword.getText();
                    AdminAccount adminAccount = new AdminAccount(date, userName, password);
                    int res = AdministratorController.addAdmin(adminAccount);
                    if (res > 0) {
                        Object[] Option = {"Login as Admin ", " New user Account"};
                        int showOptionDialog = JOptionPane.showOptionDialog(this, "Admin Account Created Succesfully. Select login mode.", "Login mode", JOptionPane.CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, Option, Option[1]);
                        if (showOptionDialog == 0) {
                            Home home = new Home();
                            home.setVisible(true);
                        } else if (showOptionDialog == 1) {
                            CreataeNewUserAccount creataeNewUserAccount=new CreataeNewUserAccount();
                            creataeNewUserAccount.setSize(loadPanel.getSize());
                            loadPanel.removeAll();
                            loadPanel.add(creataeNewUserAccount);
                            loadPanel.repaint();
                            loadPanel.revalidate();
                        }

                    }
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(NewAdminAccount.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Passwords do not match . please retry !!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "UserName is not Valid");
        }

    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtConfirmPassword6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmPassword6KeyReleased

        char[] password = txtPassword.getPassword();
        char[] confirmpassword = txtConfirmPassword6.getPassword();
        String match = "";
        if (confirmpassword.length <= password.length) {
            for (int i = 0; i < confirmpassword.length; i++) {
                if (match == "" || match == "matched") {
                    if (password[i] == confirmpassword[i]) {
                        match = "matched";
                        //                    match="matched";
                        //                    labelMatch.setText(match);
                    } else {
                        match = "mis-match";

                    }
                } else {

                }
            }
            //        if(password.length==confirmpassword.length){
            //            labelMatch.setText(match);
            //        }
        } else if (confirmpassword.length > password.length) {
            match = "longer than password";
        }
        if (confirmpassword.length == 0) {
            labelMatch2.setText("");
        } else if (password.length == confirmpassword.length) {
            labelMatch2.setText(match);
        } else if (password.length > confirmpassword.length) {
            if (match == "mis-match") {
                labelMatch2.setText(match);
            } else {
                labelMatch2.setText("");
            }
        } else if (password.length < confirmpassword.length) {
            labelMatch2.setText(match);
        }
        //        System.out.println(password);
        //        String confirmpassword=txtConfirmPassword.getPassword().toString();
        //        System.out.println(confirmpassword);
    }//GEN-LAST:event_txtConfirmPassword6KeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        //        String password=txtPassword.getSelectedText()
        //
        //                look bellow

        // methanamama ganna one count elkanam nmka hadathki matma
        //eth methan password eke akuruwalata ints letters adanguda kyala balnnannam aniwa me Strings split kranna ona
    }//GEN-LAST:event_txtPasswordKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JLabel labelMatch2;
    private javax.swing.JLabel labelStrength2;
    private javax.swing.JPanel loadPanel;
    private javax.swing.JPasswordField txtConfirmPassword6;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
