/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gateway.view.Login;

import gateway.controllers.UserAccountController;
import gateway.libraries.ComboSearch;
import gateway.view.home.Home;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pesshala
 */
public class UserAccount extends javax.swing.JPanel {

    /**
     * Creates new form UsreAccount
     */
    public UserAccount() {
        initComponents();
        loaduser();
        new ComboSearch().setSearchableCombo(comboUserName, true, "no user");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboUserName = new javax.swing.JComboBox();
        txtPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();

        setLayout(null);

        loadPanel.setOpaque(false);
        loadPanel.setLayout(null);

        jLabel1.setText("User Name  :");
        loadPanel.add(jLabel1);
        jLabel1.setBounds(122, 168, 62, 14);

        jLabel2.setText("Password  :");
        loadPanel.add(jLabel2);
        jLabel2.setBounds(128, 262, 56, 14);

        comboUserName.setEditable(true);
        comboUserName.setOpaque(false);
        loadPanel.add(comboUserName);
        comboUserName.setBounds(188, 152, 239, 30);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        loadPanel.add(txtPassword);
        txtPassword.setBounds(178, 379, 267, 20);

        jLabel3.setText("Login by Administrator account");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        loadPanel.add(jLabel3);
        jLabel3.setBounds(31, 427, 208, 28);

        jLabel4.setText("         LOGIN");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        loadPanel.add(jLabel4);
        jLabel4.setBounds(310, 288, 100, 60);

        jLabel5.setText("Create new account");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        loadPanel.add(jLabel5);
        jLabel5.setBounds(31, 466, 208, 23);

        jLabel6.setText("Exit");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        loadPanel.add(jLabel6);
        jLabel6.setBounds(590, 60, 49, 30);
        loadPanel.add(jLabel7);
        jLabel7.setBounds(597, 262, 82, 20);

        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });
        loadPanel.add(passwordfield);
        passwordfield.setBounds(200, 217, 230, 36);

        add(loadPanel);
        loadPanel.setBounds(0, 0, 650, 500);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gateway/view/images/home/login.png"))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(0, 0, 650, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        CreataeNewUserAccount creataeNewUserAccount=new CreataeNewUserAccount();
        creataeNewUserAccount.setSize(loadPanel.getSize());
        loadPanel.removeAll();
        loadPanel.add(creataeNewUserAccount);
        loadPanel.repaint();
        loadPanel.revalidate();                
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        NewAdminAccount createAdminAccount=new NewAdminAccount();
        createAdminAccount.setSize(loadPanel.getSize());
        loadPanel.removeAll();
        loadPanel.add(createAdminAccount);
        loadPanel.repaint();
        loadPanel.revalidate();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        try {
            String check=txtPassword.getText();
            String username=comboUserName.getSelectedItem().toString();
            String password=UserAccountController.getPassword(username);
            if(check.equals(password)){
                jLabel7.setText("matched");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        try {
            String userName=comboUserName.getSelectedItem().toString();
            String password=passwordfield.getText();
            boolean pass=UserAccountController.checkPassword(userName,password);
            if(pass){
                Home home =new Home();
                home.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Incorrect Passsword entered  !!");
            }
            
            
//        if(jLabel7.getText()=="matched"){
//            Home home =new Home();
//            home.setVisible(true);           
//        }
        } catch (SQLException ex) {
            Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel loadPanel;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables

    private void loaduser() {
        try {
            ArrayList<String> Users=UserAccountController.getUsers();
            
            for(String user:Users){
                   comboUserName.addItem(user);
 
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
