/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gateway.view.teacheraccount;

import gateway.controllers.MonthlyPaymentController;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pesshala
 */
public class DoPayments extends javax.swing.JPanel {
    DefaultTableModel dtmTotal;
    DefaultTableModel dtmPayed;
    private String teacherId;
    /**
     * Creates new form DoPayments
     */
    public DoPayments(String teacherId) {
        initComponents();
        dtmTotal=(DefaultTableModel)tableTotal.getModel();
        dtmPayed=(DefaultTableModel)tablePayed.getModel();
        this.teacherId=teacherId;
        loadTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePayed = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTotal = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelToBePayed = new javax.swing.JLabel();
        labelPayed = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablePayed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePayed);
        if (tablePayed.getColumnModel().getColumnCount() > 0) {
            tablePayed.getColumnModel().getColumn(0).setResizable(false);
            tablePayed.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 14, 335, 119));

        tableTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableTotal);
        if (tableTotal.getColumnModel().getColumnCount() > 0) {
            tableTotal.getColumnModel().getColumn(0).setResizable(false);
            tableTotal.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 21, 353, 110));

        jLabel1.setText("Total Payed");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel2.setText("Remaining To Be Payed");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 120, -1));

        labelToBePayed.setText(".............");
        add(labelToBePayed, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

        labelPayed.setText(".............");
        add(labelPayed, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel3.setText("Amount        :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 182, 810, 10));

        jLabel4.setText("Payment ID  :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel5.setText("Date             :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 180, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 180, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("Do Paymment");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 280, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel labelPayed;
    private javax.swing.JLabel labelToBePayed;
    private javax.swing.JTable tablePayed;
    private javax.swing.JTable tableTotal;
    // End of variables declaration//GEN-END:variables

    private void loadTables() {
        ArrayList<String[]> rowDatas=MonthlyPaymentController.getDailyAmounts(teacherId);
    }
}
