/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gateway.view.home;

import java.util.Calendar;
import static java.util.Calendar.AM_PM;
import java.util.GregorianCalendar;

/**
 *
 * @author DELL
 */
public class Clock extends javax.swing.JPanel {
    int timeRun=0;
    /**
     * Creates new form Clock
     */
    public Clock() {
        initComponents();
       
        new Thread(){
            public void run(){
                while(timeRun==0){
                    Calendar cal= new GregorianCalendar();
                    
                    int hour = cal.get(Calendar.HOUR);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    int am_pm = cal.get(Calendar.AM_PM);
                    
                    int year=cal.get(Calendar.YEAR);
                    int month= cal.get(Calendar.MONTH);
                    int day= cal.get(Calendar.DATE);
                    
                    String day_night = "";
                    if(am_pm==1){
                        day_night="PM";
                    }else{
                        day_night="AM";
                    }
                    String time= day+"-"+month+"-"+year+"       "+hour+":"+min+":"+sec+" "+day_night;
                    clockLabel.setText(time);
                }
                
            }
        
         }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clockLabel = new javax.swing.JLabel();

        setOpaque(false);

        clockLabel.setFont(new java.awt.Font("Radioland", 0, 18)); // NOI18N
        clockLabel.setForeground(new java.awt.Color(66, 149, 146));
        clockLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clockLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clockLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clockLabel;
    // End of variables declaration//GEN-END:variables
}
