/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gateway.view.home;

//import gateway.view.studentaccount.StudentAccount;
//import gateway.view.system.EditSystem;
//import gateway.view.teacheraccount.TeacherAccounts;
import gateway.report.ReportForm;
import gateway.view.studentaccount.StudentAccount;
import gateway.view.system.EditSystem;
import gateway.view.teacheraccount.TeacherAccounts;
import java.sql.SQLException;

/**
 *
 * @author DELL
 */
public class HomeEventBackground extends javax.swing.JPanel {

    /**
     * Creates new form HomeEventBackground
     */
    public HomeEventBackground(String panel) throws SQLException, ClassNotFoundException {
        initComponents();
        if (panel == "AddStudent") {
            addStudent();
        } else if (panel == "EditSystem") {
            system();
        } else if (panel == "log") {
            log();
        } else if (panel == "TimeTable") {
            timeTable();
        } else if (panel == "Reports") {
            Reports();
        }

    }

    public HomeEventBackground(String panel, String id, String name) throws SQLException, ClassNotFoundException {
        initComponents();
        if (panel == "StudentAccount") {
            studentAccount(id, name);
        } else if (panel == "TeacherAccount") {
            teacherAccount(id, name);
        }
    }

    private void addStudent() throws SQLException, ClassNotFoundException {
        AddStudent addStudent = new AddStudent();
        addStudent.setSize(loadpanel.getSize());
        loadpanel.removeAll();
        loadpanel.add(addStudent);
        loadpanel.repaint();
        loadpanel.revalidate();
    }

    private void studentAccount(String id, String name) {
        StudentAccount st = new StudentAccount(id, name);
        st.setSize(loadpanel.getSize());
        loadpanel.removeAll();
        loadpanel.add(st);
        loadpanel.repaint();
        loadpanel.revalidate();
    }

    private void system() throws SQLException, ClassNotFoundException {
        EditSystem st = new EditSystem();
        st.setSize(loadpanel.getSize());
        loadpanel.removeAll();
        loadpanel.add(st);
        loadpanel.repaint();
        loadpanel.revalidate();
    }

    private void timeTable() throws SQLException, ClassNotFoundException {
        TimeTable st = new TimeTable();
        st.setSize(loadpanel.getSize());
        loadpanel.removeAll();
        loadpanel.add(st);
        loadpanel.repaint();
        loadpanel.revalidate();
    }

    private void log() throws SQLException, ClassNotFoundException {
        LogEntry st = new LogEntry();
        st.setSize(loadpanel.getSize());
        loadpanel.removeAll();
        loadpanel.add(st);
        loadpanel.repaint();
        loadpanel.revalidate();
    }

    private void teacherAccount(String id, String name) {
        TeacherAccounts st = new TeacherAccounts(id, name);
        st.setSize(loadpanel.getSize());
        loadpanel.removeAll();
        loadpanel.add(st);
        loadpanel.repaint();
        loadpanel.revalidate();
    }

    private void Reports() {
        ReportForm st = new ReportForm();
        st.setSize(loadpanel.getSize());
        loadpanel.removeAll();
        loadpanel.add(st);
        loadpanel.repaint();
        loadpanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadpanel.setOpaque(false);
        loadpanel.setLayout(new java.awt.BorderLayout());
        add(loadpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gateway/view/images/home/home events panel.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel loadpanel;
    // End of variables declaration//GEN-END:variables

    
}
