 
         /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gateway.view.home;

//import gateway.view.studentaccount.StudentAccount;
import gateway.controllers.StudentController;
import gateway.controllers.TeacherController;
import gateway.view.studentaccount.StudentAccount;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author DELL
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form Homepanel
     */
    public HomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        componentpanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        labelTeacherAccounts = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        labelTeacherPhoto = new javax.swing.JLabel();
        txtTeacherId = new javax.swing.JTextField();
        txtTeacherName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buttonEnterTeacherAccount = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        labelEnterLog = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panelStudenttAccount = new javax.swing.JPanel();
        labelStudentAccount = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelStudentPhoto = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        txStudenttName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonEnterStudentAccount = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labelAddStudent = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelAddAndEditSystem = new javax.swing.JLabel();
        labelSitePlan = new javax.swing.JLabel();
        labelTimeTable = new javax.swing.JLabel();
        labelTimeTable1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setOpaque(false);

        componentpanel.setOpaque(false);
        componentpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);

        jPanel5.setOpaque(false);

        labelTeacherAccounts.setBackground(new java.awt.Color(255, 102, 102));
        labelTeacherAccounts.setFont(new java.awt.Font("Rexlia Free", 1, 14)); // NOI18N
        labelTeacherAccounts.setForeground(new java.awt.Color(230, 255, 255));
        labelTeacherAccounts.setText("TEACHER ACCOUNT LOGIN");
        labelTeacherAccounts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelTeacherAccounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTeacherAccountsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelTeacherAccountsMouseEntered(evt);
            }
        });

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTeacherPhoto.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.add(labelTeacherPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 113, 120));

        txtTeacherId.setFont(new java.awt.Font("Miriam", 2, 14)); // NOI18N
        txtTeacherId.setForeground(new java.awt.Color(255, 255, 255));
        txtTeacherId.setBorder(null);
        txtTeacherId.setOpaque(false);
        txtTeacherId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTeacherIdKeyReleased(evt);
            }
        });
        jPanel6.add(txtTeacherId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 230, 26));

        txtTeacherName.setFont(new java.awt.Font("Miriam", 2, 14)); // NOI18N
        txtTeacherName.setForeground(new java.awt.Color(255, 255, 255));
        txtTeacherName.setBorder(null);
        txtTeacherName.setOpaque(false);
        jPanel6.add(txtTeacherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 230, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(218, 251, 251));
        jLabel2.setText("Teacher Name : ");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        buttonEnterTeacherAccount.setContentAreaFilled(false);
        buttonEnterTeacherAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEnterTeacherAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonEnterTeacherAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonEnterTeacherAccountMouseExited(evt);
            }
        });
        jPanel6.add(buttonEnterTeacherAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 130, 100));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(218, 251, 251));
        jLabel4.setText("Serial Number : ");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelTeacherAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTeacherAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        labelEnterLog.setFont(new java.awt.Font("Techno Hideo", 1, 24)); // NOI18N
        labelEnterLog.setForeground(new java.awt.Color(231, 255, 255));
        labelEnterLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEnterLogMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelEnterLogMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelEnterLogMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(labelEnterLog, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelEnterLog, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 55, Short.MAX_VALUE))
        );

        componentpanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 380, 490));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelStudenttAccount.setOpaque(false);
        panelStudenttAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelStudenttAccountMouseClicked(evt);
            }
        });
        panelStudenttAccount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelStudentAccount.setBackground(new java.awt.Color(255, 102, 102));
        labelStudentAccount.setFont(new java.awt.Font("Rexlia Free", 1, 14)); // NOI18N
        labelStudentAccount.setForeground(new java.awt.Color(230, 255, 255));
        labelStudentAccount.setText("STUDENT ACCOUNT LOGIN   (F1)");
        labelStudentAccount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelStudentAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelStudentAccountMouseClicked(evt);
            }
        });
        labelStudentAccount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                labelStudentAccountKeyPressed(evt);
            }
        });
        panelStudenttAccount.add(labelStudentAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 320, 28));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelStudentPhoto.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(labelStudentPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 110, 100));

        txtStudentId.setFont(new java.awt.Font("Miriam", 2, 14)); // NOI18N
        txtStudentId.setForeground(new java.awt.Color(255, 255, 255));
        txtStudentId.setBorder(null);
        txtStudentId.setOpaque(false);
        txtStudentId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStudentIdKeyReleased(evt);
            }
        });
        jPanel1.add(txtStudentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 228, 26));

        txStudenttName.setFont(new java.awt.Font("Miriam", 2, 14)); // NOI18N
        txStudenttName.setForeground(new java.awt.Color(255, 255, 255));
        txStudenttName.setBorder(null);
        txStudenttName.setOpaque(false);
        jPanel1.add(txStudenttName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 228, 24));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(218, 251, 251));
        jLabel1.setText("Student Name : ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        buttonEnterStudentAccount.setContentAreaFilled(false);
        buttonEnterStudentAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEnterStudentAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonEnterStudentAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonEnterStudentAccountMouseExited(evt);
            }
        });
        buttonEnterStudentAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnterStudentAccountActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEnterStudentAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 120, 90));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(218, 251, 251));
        jLabel5.setText("Admision Number : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        panelStudenttAccount.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 50, -1, 250));

        jPanel3.add(panelStudenttAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 380, -1));

        componentpanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 370, 300));

        labelAddStudent.setFont(new java.awt.Font("Techno Hideo", 1, 24)); // NOI18N
        labelAddStudent.setForeground(new java.awt.Color(231, 255, 255));
        labelAddStudent.setToolTipText("");
        labelAddStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddStudentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelAddStudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelAddStudentMouseExited(evt);
            }
        });
        componentpanel.add(labelAddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 220, 100));

        jPanel4.setOpaque(false);

        labelAddAndEditSystem.setFont(new java.awt.Font("Techno Hideo", 1, 24)); // NOI18N
        labelAddAndEditSystem.setForeground(new java.awt.Color(231, 255, 255));
        labelAddAndEditSystem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddAndEditSystemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelAddAndEditSystemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelAddAndEditSystemMouseExited(evt);
            }
        });

        labelSitePlan.setFont(new java.awt.Font("Techno Hideo", 1, 24)); // NOI18N
        labelSitePlan.setForeground(new java.awt.Color(231, 255, 255));
        labelSitePlan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelSitePlanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelSitePlanMouseExited(evt);
            }
        });

        labelTimeTable.setFont(new java.awt.Font("Techno Hideo", 1, 24)); // NOI18N
        labelTimeTable.setForeground(new java.awt.Color(231, 255, 255));
        labelTimeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTimeTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelTimeTableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelTimeTableMouseExited(evt);
            }
        });

        labelTimeTable1.setFont(new java.awt.Font("Techno Hideo", 1, 24)); // NOI18N
        labelTimeTable1.setForeground(new java.awt.Color(231, 255, 255));
        labelTimeTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTimeTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelTimeTable1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelTimeTable1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAddAndEditSystem, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(labelTimeTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelSitePlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTimeTable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAddAndEditSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSitePlan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(labelTimeTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        componentpanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 220, 440));
        componentpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1100, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(componentpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(componentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
     
    private void labelAddStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddStudentMouseClicked
        try {
            loadPanel("AddStudent");
        } catch (SQLException ex) {
            Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelAddStudentMouseClicked

    private void labelAddAndEditSystemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddAndEditSystemMouseClicked
        try {
            loadPanel("EditSystem");
        } catch (SQLException ex) {
            Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_labelAddAndEditSystemMouseClicked

    private void labelAddStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddStudentMouseEntered
        labelAddStudent.setIcon(new javax.swing.ImageIcon("D:\\Peshala\\OOD\\Gateway\\src\\gateway\\view\\images\\home\\opaque.png")); 
    }//GEN-LAST:event_labelAddStudentMouseEntered

    private void panelStudenttAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelStudenttAccountMouseClicked
        
       
    }//GEN-LAST:event_panelStudenttAccountMouseClicked

    private void txtStudentIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStudentIdKeyReleased
     String Id=txtStudentId.getText();
     String[] student=null;
        try {
            student = StudentController.getStudent(Id);
        } catch (SQLException ex) {
            Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(student==null){ 
            txStudenttName.setText("");
            labelStudentPhoto.setIcon(new ImageIcon());
        }else{
            txStudenttName.setText(student[0]);
            labelStudentPhoto.setIcon(new ImageIcon(student[1]));
    
        }        
       
    }//GEN-LAST:event_txtStudentIdKeyReleased

    private void buttonEnterStudentAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEnterStudentAccountMouseClicked
        
        if("".equals(txStudenttName.getText())){
            
        }else{
            String id=txtStudentId.getText();
            String name=txStudenttName.getText();
            try {
            loadPanel("StudentAccount",id,name);
           
            } catch (SQLException ex) {
                 Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                  Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
          
    }//GEN-LAST:event_buttonEnterStudentAccountMouseClicked

    private void buttonEnterStudentAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnterStudentAccountActionPerformed
       
    }//GEN-LAST:event_buttonEnterStudentAccountActionPerformed

    private void buttonEnterStudentAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEnterStudentAccountMouseEntered
       buttonEnterStudentAccount.setIcon(new javax.swing.ImageIcon("D:\\Peshala\\OOD\\Gateway\\src\\gateway\\view\\images\\home\\opaque.png")); 
    }//GEN-LAST:event_buttonEnterStudentAccountMouseEntered

    private void labelTimeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTimeTableMouseClicked
        try {
            loadPanel("TimeTable");
        } catch (SQLException ex) {
            Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelTimeTableMouseClicked

    private void buttonEnterTeacherAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEnterTeacherAccountMouseClicked
        if("".equals(txtTeacherName.getText())){

        }else{
            String id=txtTeacherId.getText();
            String name=txtTeacherName.getText();
            try {
                loadPanel("TeacherAccount",id,name);
            } catch (SQLException ex) {
                Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonEnterTeacherAccountMouseClicked

    private void txtTeacherIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeacherIdKeyReleased
        String Id=txtTeacherId.getText();

        try {
            checkForTeacher(Id) ;
        } catch (SQLException ex) {
            Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtTeacherIdKeyReleased

    private void labelTeacherAccountsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTeacherAccountsMouseEntered

    }//GEN-LAST:event_labelTeacherAccountsMouseEntered

    private void labelTeacherAccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTeacherAccountsMouseClicked

    }//GEN-LAST:event_labelTeacherAccountsMouseClicked

    private void labelEnterLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEnterLogMouseClicked
        try {
            loadPanel("log");
        } catch (SQLException ex) {
            Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelEnterLogMouseClicked

    private void labelStudentAccountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_labelStudentAccountKeyPressed

    }//GEN-LAST:event_labelStudentAccountKeyPressed

    private void labelStudentAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelStudentAccountMouseClicked

    }//GEN-LAST:event_labelStudentAccountMouseClicked

    private void labelEnterLogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEnterLogMouseEntered
        labelEnterLog.setIcon(new javax.swing.ImageIcon("D:\\Peshala\\OOD\\Gateway\\src\\gateway\\view\\images\\home\\opaque.png")); 
    }//GEN-LAST:event_labelEnterLogMouseEntered

    private void labelAddAndEditSystemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddAndEditSystemMouseEntered
       labelAddAndEditSystem.setIcon(new javax.swing.ImageIcon("D:\\Peshala\\OOD\\Gateway\\src\\gateway\\view\\images\\home\\opaque.png")); 
    }//GEN-LAST:event_labelAddAndEditSystemMouseEntered

    private void labelSitePlanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSitePlanMouseEntered
       labelSitePlan.setIcon(new javax.swing.ImageIcon("D:\\Peshala\\OOD\\Gateway\\src\\gateway\\view\\images\\home\\opaque.png")); 
    }//GEN-LAST:event_labelSitePlanMouseEntered

    private void labelTimeTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTimeTableMouseEntered
       labelTimeTable.setIcon(new javax.swing.ImageIcon("D:\\Peshala\\OOD\\Gateway\\src\\gateway\\view\\images\\home\\opaque.png")); 
    }//GEN-LAST:event_labelTimeTableMouseEntered

    private void buttonEnterTeacherAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEnterTeacherAccountMouseEntered
       buttonEnterTeacherAccount.setIcon(new javax.swing.ImageIcon("D:\\Peshala\\OOD\\Gateway\\src\\gateway\\view\\images\\home\\opaque.png")); 
    }//GEN-LAST:event_buttonEnterTeacherAccountMouseEntered

    private void buttonEnterStudentAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEnterStudentAccountMouseExited
        buttonEnterStudentAccount.setIcon(new javax.swing.ImageIcon("D:\\Peshala\\OOD\\Gateway\\src\\gateway\\view\\images\\home\\transparent.png")); 
    }//GEN-LAST:event_buttonEnterStudentAccountMouseExited

    private void labelAddStudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddStudentMouseExited
       labelAddStudent.setIcon(new javax.swing.ImageIcon("D:\\Peshala\\OOD\\Gateway\\src\\gateway\\view\\images\\home\\transparent.png")); 
    }//GEN-LAST:event_labelAddStudentMouseExited

    private void labelEnterLogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEnterLogMouseExited
         labelEnterLog.setIcon(new javax.swing.ImageIcon("D:\\Peshala\\OOD\\Gateway\\src\\gateway\\view\\images\\home\\transparent.png")); 
    }//GEN-LAST:event_labelEnterLogMouseExited

    private void buttonEnterTeacherAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEnterTeacherAccountMouseExited
        buttonEnterTeacherAccount.setIcon(new javax.swing.ImageIcon("D:\\Peshala\\OOD\\Gateway\\src\\gateway\\view\\images\\home\\transparent.png")); 
    }//GEN-LAST:event_buttonEnterTeacherAccountMouseExited

    private void labelAddAndEditSystemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddAndEditSystemMouseExited
         labelAddAndEditSystem.setIcon(new javax.swing.ImageIcon("D:\\Peshala\\OOD\\Gateway\\src\\gateway\\view\\images\\home\\transparent.png")); 
    }//GEN-LAST:event_labelAddAndEditSystemMouseExited

    private void labelSitePlanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSitePlanMouseExited
       labelSitePlan.setIcon(new javax.swing.ImageIcon("D:\\Peshala\\OOD\\Gateway\\src\\gateway\\view\\images\\home\\transparent.png")); 
    }//GEN-LAST:event_labelSitePlanMouseExited

    private void labelTimeTableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTimeTableMouseExited
         labelTimeTable.setIcon(new javax.swing.ImageIcon("D:\\Peshala\\OOD\\Gateway\\src\\gateway\\view\\images\\home\\transparent.png")); 
    }//GEN-LAST:event_labelTimeTableMouseExited

    private void labelTimeTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTimeTable1MouseClicked
        try {
            loadPanel("Reports");
        } catch (SQLException ex) {
            Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelTimeTable1MouseClicked

    private void labelTimeTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTimeTable1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelTimeTable1MouseEntered

    private void labelTimeTable1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTimeTable1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelTimeTable1MouseExited
                
 
    private void checkForTeacher(String Id) throws SQLException, ClassNotFoundException{
        String[] teacher=TeacherController.getTeacher(Id);
        if(teacher==null){     
             txtTeacherName.setText("");
            labelTeacherPhoto.setIcon(new ImageIcon());
        }else{
            txtTeacherName.setText(teacher[0]);
            labelTeacherPhoto.setIcon(new ImageIcon(teacher[1]));
    
        }        
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEnterStudentAccount;
    private javax.swing.JButton buttonEnterTeacherAccount;
    private javax.swing.JPanel componentpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelAddAndEditSystem;
    private javax.swing.JLabel labelAddStudent;
    private javax.swing.JLabel labelEnterLog;
    private javax.swing.JLabel labelSitePlan;
    private javax.swing.JLabel labelStudentAccount;
    private javax.swing.JLabel labelStudentPhoto;
    private javax.swing.JLabel labelTeacherAccounts;
    private javax.swing.JLabel labelTeacherPhoto;
    private javax.swing.JLabel labelTimeTable;
    private javax.swing.JLabel labelTimeTable1;
    private javax.swing.JPanel panelStudenttAccount;
    private javax.swing.JTextField txStudenttName;
    private javax.swing.JTextField txtStudentId;
    private javax.swing.JTextField txtTeacherId;
    private javax.swing.JTextField txtTeacherName;
    // End of variables declaration//GEN-END:variables


   private void loadPanel(String panel) throws SQLException, ClassNotFoundException{
      HomeEventBackground homeeventbackground =new HomeEventBackground(panel);
      homeeventbackground.setSize(componentpanel.getSize());
      componentpanel.removeAll();
      // System.out.println("helllo");
      componentpanel.add(homeeventbackground);
      componentpanel.repaint();
      componentpanel.revalidate();
   }
   private void loadPanel(String panel,String id,String name) throws SQLException, ClassNotFoundException{
      HomeEventBackground homeeventbackground =new HomeEventBackground(panel,id,name);
      homeeventbackground.setSize(componentpanel.getSize());
      componentpanel.removeAll();
      componentpanel.add(homeeventbackground);
      componentpanel.repaint();
      componentpanel.revalidate();
   }
}
