/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gateway.view.home;



import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DELL
 */
public class Home extends javax.swing.JFrame {
    
    private static Home home;
    
    public static Home getHomePage() {
        if(home==null){
            home=new Home();
        }
        return home;
    }

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        home=this;
        loadMainPanel();
        attendance();
        time();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainpanel = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        labelhome = new javax.swing.JLabel();
        labelsystem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        attendancepanel = new javax.swing.JPanel();
        time = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        backgroundlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainpanel.setOpaque(false);
        mainpanel.setLayout(new java.awt.BorderLayout());
        jPanel1.add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1100, 560));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, 30, 20));

        labelhome.setText("HOME");
        labelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelhomeMouseClicked(evt);
            }
        });
        jPanel1.add(labelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 50, 40));

        labelsystem.setText("SYSTEM");
        labelsystem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelsystemMouseClicked(evt);
            }
        });
        jPanel1.add(labelsystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 690, 50, 30));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, 30, 20));

        attendancepanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        attendancepanel.setOpaque(false);

        javax.swing.GroupLayout attendancepanelLayout = new javax.swing.GroupLayout(attendancepanel);
        attendancepanel.setLayout(attendancepanelLayout);
        attendancepanelLayout.setHorizontalGroup(
            attendancepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        attendancepanelLayout.setVerticalGroup(
            attendancepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanel1.add(attendancepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 120, 260, 560));

        time.setOpaque(false);

        javax.swing.GroupLayout timeLayout = new javax.swing.GroupLayout(time);
        time.setLayout(timeLayout);
        timeLayout.setHorizontalGroup(
            timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        timeLayout.setVerticalGroup(
            timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 680, 290, 40));

        jLabel2.setText("LockScreen");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 690, 70, 30));

        backgroundlabel.setIcon(new javax.swing.ImageIcon("D:\\Peshala\\OOD\\Gateway\\src\\gateway\\view\\images\\home\\home 07 .19_1.png")); // NOI18N
        jPanel1.add(backgroundlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1362, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void labelsystemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelsystemMouseClicked
        try {
            loadSystemPanel();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelsystemMouseClicked

    private void labelhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelhomeMouseClicked
        loadMainPanel();
    }//GEN-LAST:event_labelhomeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(1);
    }//GEN-LAST:event_exitMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       LockScreen lockscreen=new LockScreen();
       lockscreen.setVisible(true);
       lockscreen.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel2MouseClicked
    private void attendance(){
        try {
            attendancepanel.removeAll();
            MarkAndIssueCard1 attendance=new MarkAndIssueCard1();
            attendance.setSize(attendancepanel.getSize());
            attendancepanel.add(attendance);
            attendancepanel.repaint();
            attendancepanel.revalidate();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }  
    public void loadMainPanel() {
        mainpanel.removeAll();
        HomePanel homepanel = new HomePanel();
        homepanel.setSize(mainpanel.getSize());
        mainpanel.add(homepanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }
    private void time(){
        time.removeAll();
        Clock clock=new Clock();
        clock.setSize(time.getSize());
        time.add (clock);
        time.repaint();
        time.revalidate();
        
    }
    
    public void loadSystemPanel() throws SQLException, ClassNotFoundException {
//        loadPanel("EditSystem");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
       private void loadPanel(String panel) throws SQLException, ClassNotFoundException{
//      HomeEventBackground homeeventbackground =new HomeEventBackground(panel);
//      homeeventbackground.setSize(mainpanel.getSize());
//      mainpanel.removeAll();
//      mainpanel.add(homeeventbackground);
//      mainpanel.repaint();
//      mainpanel.revalidate();
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel attendancepanel;
    private javax.swing.JLabel backgroundlabel;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelhome;
    private javax.swing.JLabel labelsystem;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel time;
    // End of variables declaration//GEN-END:variables
}
