/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gateway.view.home;

import gateway.controllers.ClassController;
import gateway.controllers.CourseController;
import gateway.controllers.GradeController;
import gateway.controllers.LogController;
import gateway.controllers.SubjectController;
import gateway.controllers.TeacherController;
import gateway.libraries.ClearFields;
import gateway.libraries.CurInstance;

import gateway.model.Log;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class LogEntry extends javax.swing.JPanel {

    /**
     * Creates new form Log
     */
    private boolean ifConstructorRun = false;

    public LogEntry() throws SQLException, ClassNotFoundException {
        initComponents();
        date();
        time();
        setComboBoxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelclass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        combosubject = new javax.swing.JComboBox();
        combograde = new javax.swing.JComboBox();
        combocourse = new javax.swing.JComboBox();
        comboclass = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtToday = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaEnter = new javax.swing.JTextArea();
        btnEnterLog = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker3 = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        comboteacher = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();

        setOpaque(false);

        jPanel1.setOpaque(false);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Course  :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(310, 50, 60, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Class  :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(500, 50, 50, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Subject      :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(86, 37, 80, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Teacher       :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(80, 80, 79, 15);

        jPanel2.setOpaque(false);

        labelclass.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelclass.setText("..............................");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("LOG OF");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelclass, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(labelclass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(692, 11, 400, 77);

        combosubject.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combosubjectItemStateChanged(evt);
            }
        });
        jPanel3.add(combosubject);
        combosubject.setBounds(180, 30, 86, 20);

        combograde.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combogradeItemStateChanged(evt);
            }
        });
        jPanel3.add(combograde);
        combograde.setBounds(180, 60, 86, 20);

        combocourse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combocourseItemStateChanged(evt);
            }
        });
        jPanel3.add(combocourse);
        combocourse.setBounds(370, 20, 100, 60);

        comboclass.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboclassItemStateChanged(evt);
            }
        });
        jPanel3.add(comboclass);
        comboclass.setBounds(556, 10, 130, 90);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Select Class");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 0, 210, 29);

        jPanel4.setOpaque(false);

        jPanel6.setLayout(null);

        txtToday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel6.add(txtToday);
        txtToday.setBounds(80, 10, 117, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Time");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(220, 10, 50, 15);
        jPanel6.add(txtTime);
        txtTime.setBounds(290, 10, 79, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Date ");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(20, 10, 50, 15);

        btnCancel.setText("CANCEL");
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAreaEnter.setColumns(20);
        txtAreaEnter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAreaEnter.setRows(5);
        jScrollPane1.setViewportView(txtAreaEnter);

        btnEnterLog.setText("ENTER LOG");
        btnEnterLog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEnterLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnterLogMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnEnterLog, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnterLog, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Enter Log", jPanel4);

        jPanel5.setOpaque(false);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Select Time Duration to View");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 10));

        jLabel14.setText("From   :");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel15.setText("To      :");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 43, -1));
        jPanel7.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 140, 10));

        jRadioButton1.setText("Past Month");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jRadioButton2.setText("Last Day");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jRadioButton3.setText("  Date:");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jRadioButton4.setText("Full Log");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));
        jPanel7.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 140, 10));
        jPanel7.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, 10));
        jPanel7.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, 140, 10));

        jXDatePicker1.setDate(null);
        jPanel7.add(jXDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 110, -1));

        jXDatePicker2.setDate(null);
        jPanel7.add(jXDatePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 110, -1));

        jXDatePicker3.setDate(null);
        jPanel7.add(jXDatePicker3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 110, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Log"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton1.setText(">");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );

        jTabbedPane1.addTab("View Log", jPanel5);

        jPanel3.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 107, 1100, 467);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setText(">");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(470, 30, 30, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setText(">");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(280, 30, 30, 40);

        comboteacher.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboteacherItemStateChanged(evt);
            }
        });
        jPanel3.add(comboteacher);
        comboteacher.setBounds(180, 80, 86, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Grade        :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(90, 60, 80, 15);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void date() {

        txtToday.setText(CurInstance.Date_day());
    }

    private void time() {

        txtTime.setText(CurInstance.Time_12_AMPM());

    }

    private void setComboBoxes() throws SQLException, ClassNotFoundException {
        setSubject();
        setGrade();
        setTeacher();
        setCourse();
        setClas();
        ifConstructorRun = true;

    }

    private void setSubject() throws SQLException, ClassNotFoundException {
        ArrayList<String[]> subjects = SubjectController.getSubject();
        for (String[] subject : subjects) {
            combosubject.addItem(subject[0]);
        }
    }

    private void setGrade() throws SQLException, ClassNotFoundException {

        ArrayList<String[]> grades = GradeController.getGrade();
        for (String[] grade : grades) {
            combograde.addItem(grade[0]);
        }
    }

    private void setTeacher() throws SQLException, ClassNotFoundException {
        ArrayList<String[]> teachers = TeacherController.getTeacherName();
        for (String[] teacher : teachers) {
            comboteacher.addItem(teacher[0]);
        }
    }

    private void setCourse() throws SQLException, ClassNotFoundException {
        ArrayList<String[]> courses = CourseController.getCourse();
        for (String[] course : courses) {
            combocourse.addItem(course[0]);
        }
    }

    private void setClas() throws SQLException, ClassNotFoundException {

        ArrayList<String[]> classes = ClassController.getClas();
        for (String[] clas : classes) {                  //didnt use class becouse its a keywaord
            comboclass.addItem(clas[0]);
        }

    }

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void btnEnterLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterLogMouseClicked
        try {
            String classId = ClassController.getClassId(comboclass.getSelectedItem().toString());
            String date = txtToday.getText();
            String time = txtTime.getText();
            String content = txtAreaEnter.getText();

            Log log = new Log(classId, date, time, content);

            int res = LogController.enterLog(log);
            if (res < 0) {
                JOptionPane.showMessageDialog(null, "Log Succesfully Entered");
            } else {
                JOptionPane.showMessageDialog(null, "Entry Unsuccesfull");
            }

            setComboBoxes();
            ArrayList<JTextField> fields = new ArrayList<>();
            fields.add(txtTime);
            fields.add(txtToday);
            ClearFields.clearTxtField(fields);

        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(LogEntry.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEnterLogMouseClicked

    private void combosubjectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combosubjectItemStateChanged
//        String subject=combosubject.getSelectedItem().toString();
//        String grade=combograde.getSelectedItem().toString();
        if (ifConstructorRun) {
            try {
                String teacher = TeacherController.getTeacherId(comboteacher.getSelectedItem().toString());
                String subject = SubjectController.getSubjectId(combosubject.getSelectedItem().toString());
                String grade = GradeController.getGradeId(combograde.getSelectedItem().toString());

                ArrayList<String> courses = CourseController.getFilteredCourses(teacher, subject, grade);
                for (String course : courses) {
                    combocourse.removeAll();
                    combocourse.addItem(course);
                }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(LogEntry.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_combosubjectItemStateChanged

    private void comboteacherItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboteacherItemStateChanged
        if (ifConstructorRun) {
            try {
                String teacher = TeacherController.getTeacherId(comboteacher.getSelectedItem().toString());
                String subject = SubjectController.getSubjectId(combosubject.getSelectedItem().toString());
                String grade = GradeController.getGradeId(combograde.getSelectedItem().toString());

                ArrayList<String> courses = CourseController.getFilteredCourses(teacher, subject, grade);
                for (String course : courses) {
                    combocourse.removeAll();
                    combocourse.addItem(course);
                }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(LogEntry.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_comboteacherItemStateChanged

    private void combocourseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combocourseItemStateChanged
        if (ifConstructorRun) {
            try {
                String courseId = CourseController.getCourseId(combocourse.getSelectedItem().toString());
                ArrayList<String> classes = ClassController.getClassesOfCourse(courseId);
                for (String clas : classes) {
                    comboclass.removeAll();
                    comboclass.addItem(clas.toString());
                }
            } catch (SQLException ex) {
                Logger.getLogger(LogEntry.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(LogEntry.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_combocourseItemStateChanged

    private void comboclassItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboclassItemStateChanged
        String clas = comboclass.getSelectedItem().toString();
        labelclass.setText(clas);

    }//GEN-LAST:event_comboclassItemStateChanged

    private void combogradeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combogradeItemStateChanged
        if (ifConstructorRun) {
            try {
                String teacher = TeacherController.getTeacherId(comboteacher.getSelectedItem().toString());
                String subject = SubjectController.getSubjectId(combosubject.getSelectedItem().toString());
                String grade = GradeController.getGradeId(combograde.getSelectedItem().toString());

                ArrayList<String> courses = CourseController.getFilteredCourses(teacher, subject, grade);
                for (String course : courses) {
                    combocourse.removeAll();
                    combocourse.addItem(course);
                }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(LogEntry.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_combogradeItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnEnterLog;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox comboclass;
    private javax.swing.JComboBox combocourse;
    private javax.swing.JComboBox combograde;
    private javax.swing.JComboBox combosubject;
    private javax.swing.JComboBox comboteacher;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker3;
    private javax.swing.JLabel labelclass;
    private javax.swing.JTextArea txtAreaEnter;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtToday;
    // End of variables declaration//GEN-END:variables

}
