/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gateway.view.home;

import gateway.controllers.PlaceController;
import gateway.controllers.TimetableController;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
/**
 *
 * @author DELL
 */
public class TimeTable extends javax.swing.JPanel {
DefaultTableModel dtm;

    /**
     * Creates new form Table
     */
    public TimeTable() throws SQLException, ClassNotFoundException {
        initComponents();
        loadCombo();
        dtm=(DefaultTableModel)table.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        comboplace = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"08.00  -  08.30", null, null, null, null, null, null, null},
                {"08.30  -  09.00", null, null, null, null, null, null, null},
                {"09.00  -  09.30", null, null, null, null, null, null, null},
                {"09.30-10.00", null, null, null, null, null, null, null},
                {"10.00  -  10.30", null, null, null, null, null, null, null},
                {"10.30  -  11.00", null, null, null, null, null, null, null},
                {"11.00  -  11.30", null, null, null, null, null, null, null},
                {"11.30  -  12.00", null, null, null, null, null, null, null},
                {"12.00  -  12.30", null, null, null, null, null, null, null},
                {"12.30  -  01.00", null, null, null, null, null, null, null},
                {"01.00  -  01.30", null, null, null, null, null, null, null},
                {"01.30  -  02.00", null, null, null, null, null, null, null},
                {"02.00  -  02.30", null, null, null, null, null, null, null},
                {"02.30  -  03.00", null, null, null, null, null, null, null},
                {"03.00  -  03.30", null, null, null, null, null, null, null},
                {"03.30  -  04.00", null, null, null, null, null, null, null},
                {"04.00  -  04.30", null, null, null, null, null, null, null},
                {"04.30  -  05.00", null, null, null, null, null, null, null},
                {"05.00  -  05.30", null, null, null, null, null, null, null},
                {"05.30  -  06.00", null, null, null, null, null, null, null},
                {"06.00  -  06.30", null, null, null, null, null, null, null},
                {"06.30  -  07.00", null, null, null, null, null, null, null},
                {"07.00  -  07.30", null, null, null, null, null, null, null},
                {"07.30  -  08.00", null, null, null, null, null, null, null},
                {"08.00  -  08.30", null, null, null, null, null, null, null},
                {"08.30  -  09.00", null, null, null, null, null, null, null},
                {"09.00  -  09.30", null, null, null, null, null, null, null},
                {"09.30  -  10.00", null, null, null, null, null, null, null}
            },
            new String [] {
                "Period", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jButton1.setText("Show TimeTable");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Hall        :");

        jButton2.setText("Add new Class");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(comboplace, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jButton1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 550));
    }// </editor-fold>//GEN-END:initComponents
    private void loadCombo() throws SQLException, ClassNotFoundException{
        ArrayList<String> places=PlaceController.getPlaces();
        for(String place:places){
            //String cell=(String)place[];
            comboplace.addItem(place);
        }    
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        loadTable();
    } catch (SQLException ex) {
        Logger.getLogger(TimeTable.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(TimeTable.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        ExternalViewer externalViewer=new  ExternalViewer("AddClass");
        externalViewer.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

private void loadTable() throws SQLException, ClassNotFoundException{
    System.out.println(comboplace.getSelectedItem().toString());
    String place=PlaceController.getPlaceId(comboplace.getSelectedItem().toString());
    System.out.println(place+place+place);
    String[][] rowData=TimetableController.getTimetable(place);
    for(int i=0;i<7;i++){
        for(int j=0;j<28;j++){
            //String cell=rowData[i][j].toString();
            if(rowData[i][j]==(null)){
                dtm.setValueAt(null, j, i+1);
            }else{
                dtm.setValueAt(rowData[i][j].toString(), j,i+1);
            }
            
        }
    }
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboplace;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
