/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gateway.view.system;

import gateway.controllers.CourseController;
import gateway.controllers.FurnitureController;
import gateway.controllers.GradeController;
import gateway.controllers.MultimediaController;
import gateway.controllers.PlaceController;
import gateway.controllers.SubjectController;
import gateway.controllers.TeacherController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author DELL
 */
public class AddClass extends javax.swing.JPanel {

    DefaultListModel dlm = new DefaultListModel();
    ArrayList<String[]> teachers;
    private boolean isConstructorRun=false;

    /**
     * Creates new form AddClass
     */
    public AddClass() throws SQLException, ClassNotFoundException {
        initComponents();
        teachers = TeacherController.getTeacherIDName();
        loadComboBoxes();
        listVenue.setModel(dlm);
        isConstructorRun=true;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listVenue = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        checkTeacher = new javax.swing.JCheckBox();
        checkGrade = new javax.swing.JCheckBox();
        checkSubject = new javax.swing.JCheckBox();
        checkPlace = new javax.swing.JCheckBox();
        checkTime = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel17 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        radioBtnNonAC = new javax.swing.JRadioButton();
        radioBtnAC = new javax.swing.JRadioButton();
        comboMultimedia = new javax.swing.JComboBox();
        comboFurniture = new javax.swing.JComboBox();
        txtCrowd = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        btnVenueDone = new javax.swing.JButton();
        btnFurnitureDescription = new javax.swing.JButton();
        btnMultimediaDescription = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        comboSubject = new javax.swing.JComboBox();
        comboGrade = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        comboTeacherId = new javax.swing.JComboBox();
        comboTeacherName = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        btnColoumnDone = new javax.swing.JButton();
        panelback = new javax.swing.JPanel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane5.setViewportView(listVenue);

        jLabel3.setText("methana select krana item eke placeID ek argument ekak idiyata yawanna ona time table constructor ekats ");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 250, 540));

        jLabel37.setText("Select Course");

        jLabel38.setText("Selectvenue");

        checkTeacher.setText("Teacher");

        checkGrade.setText("Grade");
        checkGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGradeActionPerformed(evt);
            }
        });

        checkSubject.setText("Subject");
        checkSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSubjectActionPerformed(evt);
            }
        });

        checkPlace.setText("Select Place");
        checkPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPlaceActionPerformed(evt);
            }
        });

        checkTime.setText("Select time ");
        checkTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addGap(0, 95, Short.MAX_VALUE)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkSubject)
                                    .addComponent(checkGrade)
                                    .addComponent(checkTeacher))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                                .addComponent(checkPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkTime, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel37)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkTeacher)
                .addGap(18, 18, 18)
                .addComponent(checkGrade)
                .addGap(18, 18, 18)
                .addComponent(checkSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkPlace)
                .addGap(18, 18, 18)
                .addComponent(checkTime)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("methana\nkaranna wenne \n,course eka select\n karama done kyala \nbutton ekak click \nkranna enna ona , \neka click krama me\n fields tikatta udin\n pannel ekak awith\n half visible krana oa");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setText("Select Course");
        jPanel17.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel18MouseClicked(evt);
            }
        });

        radioBtnNonAC.setText("Non-AC");
        radioBtnNonAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnNonACActionPerformed(evt);
            }
        });

        radioBtnAC.setText("AC");

        comboFurniture.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFurnitureItemStateChanged(evt);
            }
        });

        jLabel47.setText("Multimedia");

        jLabel44.setText("Furniture");

        jLabel46.setText("Crowd");

        jLabel49.setText("Nessasities");

        jLabel40.setText("Select Venue");

        btnVenueDone.setText("Done");

        btnFurnitureDescription.setText("Furniture descriptions >");
        btnFurnitureDescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFurnitureDescriptionMouseClicked(evt);
            }
        });
        btnFurnitureDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFurnitureDescriptionActionPerformed(evt);
            }
        });

        btnMultimediaDescription.setText("Multimedia descriptions >");
        btnMultimediaDescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMultimediaDescriptionMouseClicked(evt);
            }
        });
        btnMultimediaDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultimediaDescriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jLabel40)
                .addGap(0, 448, Short.MAX_VALUE))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(393, Short.MAX_VALUE))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(radioBtnAC)
                        .addGap(41, 41, 41)
                        .addComponent(radioBtnNonAC))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel44)
                            .addComponent(jLabel47))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboMultimedia, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboFurniture, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCrowd, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnVenueDone, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMultimediaDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFurnitureDescription))
                        .addGap(18, 18, 18))))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel49)
                .addGap(18, 18, 18)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(comboFurniture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFurnitureDescription))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(comboMultimedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMultimediaDescription))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioBtnAC)
                            .addComponent(radioBtnNonAC))
                        .addGap(43, 43, 43))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCrowd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVenueDone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 510, 270));

        jPanel19.setLayout(null);

        jPanel19.add(comboSubject);
        comboSubject.setBounds(115, 141, 178, 20);

        jPanel19.add(comboGrade);
        comboGrade.setBounds(115, 94, 178, 20);

        jLabel39.setText("Teacher ID");
        jPanel19.add(jLabel39);
        jLabel39.setBounds(20, 14, 53, 14);

        jLabel45.setText("Teacher Name");
        jPanel19.add(jLabel45);
        jLabel45.setBounds(20, 52, 69, 14);

        jLabel42.setText("Grade");
        jPanel19.add(jLabel42);
        jLabel42.setBounds(20, 97, 29, 14);

        jLabel41.setText("Subject");
        jPanel19.add(jLabel41);
        jLabel41.setBounds(20, 144, 36, 14);
        jPanel19.add(jSeparator9);
        jSeparator9.setBounds(10, 0, 90, 10);

        comboTeacherId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTeacherIdItemStateChanged(evt);
            }
        });
        jPanel19.add(comboTeacherId);
        comboTeacherId.setBounds(115, 11, 178, 20);

        comboTeacherName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTeacherNameItemStateChanged(evt);
            }
        });
        jPanel19.add(comboTeacherName);
        comboTeacherName.setBounds(115, 49, 178, 20);

        jLabel2.setText("Courses");
        jPanel19.add(jLabel2);
        jLabel2.setBounds(379, 52, 39, 14);

        jPanel19.add(jComboBox1);
        jComboBox1.setBounds(321, 75, 169, 20);

        btnColoumnDone.setText("Done");
        btnColoumnDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnColoumnDoneMouseClicked(evt);
            }
        });
        btnColoumnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColoumnDoneActionPerformed(evt);
            }
        });
        jPanel19.add(btnColoumnDone);
        btnColoumnDone.setBounds(321, 172, 132, 37);

        javax.swing.GroupLayout panelbackLayout = new javax.swing.GroupLayout(panelback);
        panelback.setLayout(panelbackLayout);
        panelbackLayout.setHorizontalGroup(
            panelbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        panelbackLayout.setVerticalGroup(
            panelbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jPanel19.add(panelback);
        panelback.setBounds(0, 0, 510, 220);

        jPanel17.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 510, 220));

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(537, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(60, 60, 60)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 560, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkGradeActionPerformed

    private void checkSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkSubjectActionPerformed

    private void checkPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPlaceActionPerformed

    private void checkTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkTimeActionPerformed

    private void radioBtnNonACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnNonACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnNonACActionPerformed

    private void btnFurnitureDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFurnitureDescriptionActionPerformed

    }//GEN-LAST:event_btnFurnitureDescriptionActionPerformed

    private void btnColoumnDoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColoumnDoneMouseClicked

    }//GEN-LAST:event_btnColoumnDoneMouseClicked

    private void jPanel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseClicked
        int crowd = Integer.parseInt(txtCrowd.getText());
        String furniture = comboFurniture.getSelectedItem().toString();
        String multimedia = comboMultimedia.getSelectedItem().toString();
        String AC;
        if (radioBtnAC.isSelected()) {
            AC = "AC";
        } else {
            AC = "Non-AC";
        }
        try {
            ArrayList<String> places = PlaceController.filterPlace(crowd, furniture, multimedia, AC);
            for (String place : places) {
                dlm.addElement(place);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddClass.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jPanel18MouseClicked

    private void comboTeacherIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTeacherIdItemStateChanged
        if (isConstructorRun) {
            comboTeacherName.setSelectedIndex(comboTeacherId.getSelectedIndex());
            try {
                filterCourse();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(AddClass.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_comboTeacherIdItemStateChanged

    private void comboTeacherNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTeacherNameItemStateChanged
        comboTeacherId.setSelectedIndex(comboTeacherName.getSelectedIndex());
    }//GEN-LAST:event_comboTeacherNameItemStateChanged

    private void comboFurnitureItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFurnitureItemStateChanged
        try {
            String furnitureid = FurnitureController.getFurnitureId(comboFurniture.getSelectedItem().toString());
            String multimediaid = MultimediaController.getMultimediaId(comboMultimedia.getSelectedItem().toString());
            int crowd = Integer.parseInt(txtCrowd.getText());
            String AC;
            if (radioBtnAC.isSelected()) {
                AC = "AC";
            } else {
                AC = "Non-AC";
            }
            ArrayList<String> places = PlaceController.filterPlace(crowd, furnitureid, multimediaid, AC);
            for (String place : places) {
                dlm.addElement(place);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddClass.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddClass.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_comboFurnitureItemStateChanged

    private void btnMultimediaDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultimediaDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMultimediaDescriptionActionPerformed

    private void btnFurnitureDescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFurnitureDescriptionMouseClicked
        FurnitureDescription furnituredescription = new FurnitureDescription();
        furnituredescription.setVisible(true);

    }//GEN-LAST:event_btnFurnitureDescriptionMouseClicked

    private void btnMultimediaDescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultimediaDescriptionMouseClicked
        MultimediaDescription multimediadescription = new MultimediaDescription();
        multimediadescription.setVisible(true);
    }//GEN-LAST:event_btnMultimediaDescriptionMouseClicked

    private void btnColoumnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColoumnDoneActionPerformed

    }//GEN-LAST:event_btnColoumnDoneActionPerformed
    private void loadComboBoxes() throws SQLException, ClassNotFoundException {
        teacherID();
        teacherName();
        subject();
        grade();
        furniture();
        multimedia();
    }

    private void teacherID() throws SQLException, ClassNotFoundException {
//        ArrayList<String[]> teachers= TeacherController.getTeacherID();
        for (String[] teacher : teachers) {
            comboTeacherId.addItem(teacher[0]);
        }
    }

    private void teacherName() throws SQLException, ClassNotFoundException {
//        ArrayList<String[]> teachers= TeacherController.getTeacherName();
        for (String[] teacher : teachers) {
            comboTeacherName.addItem(teacher[1]);
        }
    }

    private void subject() throws SQLException, ClassNotFoundException {
        ArrayList<String[]> subjects = SubjectController.getSubject();
        for (String[] subject : subjects) {
            comboSubject.addItem(subject);
        }
    }

    private void grade() throws SQLException, ClassNotFoundException {
        ArrayList<String[]> grades = GradeController.getGrade();
        for (String[] grade : grades) {
            comboGrade.addItem(grade);
        }
    }

    private void furniture() throws SQLException, ClassNotFoundException {
        ArrayList<String[]> furnitures = FurnitureController.getFurniture();
        for (String[] furniture : furnitures) {
            comboFurniture.addItem(furniture);
        }
    }

    private void multimedia() throws SQLException, ClassNotFoundException {
        ArrayList<String[]> medias = MultimediaController.getMultimedia();
        for (String[] media : medias) {
            comboTeacherId.addItem(media);
        }
    }

    private void filterCourse() throws SQLException, ClassNotFoundException {
        String teacherID = comboTeacherId.getSelectedItem().toString();
        String gradeID = GradeController.getGradeId(comboGrade.getSelectedItem().toString());
        String subjectID = SubjectController.getSubjectId(comboSubject.getSelectedItem().toString());
        ArrayList<String[]> courses = CourseController.viewFilteredCourse(gradeID, subjectID, teacherID);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColoumnDone;
    private javax.swing.JButton btnFurnitureDescription;
    private javax.swing.JButton btnMultimediaDescription;
    private javax.swing.JButton btnVenueDone;
    private javax.swing.JCheckBox checkGrade;
    private javax.swing.JCheckBox checkPlace;
    private javax.swing.JCheckBox checkSubject;
    private javax.swing.JCheckBox checkTeacher;
    private javax.swing.JCheckBox checkTime;
    private javax.swing.JComboBox comboFurniture;
    private javax.swing.JComboBox comboGrade;
    private javax.swing.JComboBox comboMultimedia;
    private javax.swing.JComboBox comboSubject;
    private javax.swing.JComboBox comboTeacherId;
    private javax.swing.JComboBox comboTeacherName;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList listVenue;
    private javax.swing.JPanel panelback;
    private javax.swing.JRadioButton radioBtnAC;
    private javax.swing.JRadioButton radioBtnNonAC;
    private javax.swing.JTextField txtCrowd;
    // End of variables declaration//GEN-END:variables
}
