/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gateway.view.system;

import gateway.controllers.PlaceController;
import gateway.model.Place;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class AddPlace extends javax.swing.JPanel {
    private DefaultTableModel dtm;
    /**
     * Creates new form AddPlace
     */
    public AddPlace() throws SQLException, ClassNotFoundException {
        initComponents();
        dtm=(DefaultTableModel)tableView.getModel();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupAC = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtAdresss = new javax.swing.JTextArea();
        comboFurniture = new javax.swing.JComboBox();
        txtId = new javax.swing.JTextField();
        txtCrowd = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        tableView = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        radioBtnNonAC = new javax.swing.JRadioButton();
        radioBtnAC = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboMultimedia = new javax.swing.JComboBox();
        btnAddPlace = new javax.swing.JLabel();

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setText("Place ID");
        jPanel8.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel50.setText("Maximum Crowd");
        jPanel8.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel51.setText("Multimedia");
        jPanel8.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel53.setText("Description");
        jPanel8.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel54.setText("Furniture Type");
        jPanel8.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txtAdresss.setColumns(20);
        txtAdresss.setRows(5);
        jScrollPane7.setViewportView(txtAdresss);

        jPanel8.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 90, 177, -1));

        comboFurniture.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel8.add(comboFurniture, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 180, -1));
        jPanel8.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 52, 177, -1));
        jPanel8.add(txtCrowd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 177, -1));

        tableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Place ID ", "Position description", "Max Crowd", "Furniture", "Multimedia", "AC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tableView);

        jPanel8.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 600, 170));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("ADD PLACE");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        btngroupAC.add(radioBtnNonAC);
        radioBtnNonAC.setText("Non-AC");

        btngroupAC.add(radioBtnAC);
        radioBtnAC.setText("AC");
        radioBtnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnACActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(radioBtnAC)
                .addGap(34, 34, 34)
                .addComponent(radioBtnNonAC)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnAC)
                    .addComponent(radioBtnNonAC))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 290, 40));

        jLabel2.setText("ADD Multimedia");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        jLabel4.setText("ADD furniture");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        comboMultimedia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMultimedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMultimediaActionPerformed(evt);
            }
        });
        jPanel8.add(comboMultimedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 180, -1));

        btnAddPlace.setText("ADD PLACE");
        btnAddPlace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAddPlace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddPlaceMouseClicked(evt);
            }
        });
        jPanel8.add(btnAddPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioBtnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnACActionPerformed

    private void comboMultimediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMultimediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMultimediaActionPerformed

    private void btnAddPlaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPlaceMouseClicked
        String id =txtId.getText();
        String position =txtAdresss.getText();
        int crowd =Integer.parseInt(txtCrowd.getText());
        String furniture =comboFurniture.getSelectedItem().toString() ;
        String multimedia= comboMultimedia.getSelectedItem().toString();
        String AC;
        if(radioBtnAC.isSelected()){
            AC="AC";
        }else{
            AC="Non-AC";
        }

        Place place=new Place(id,position,crowd,furniture,multimedia,AC);
        try {
            int res=PlaceController.addPlace(place);
            if(res>0){
                JOptionPane.showMessageDialog(null,"Place Added Succesfully");
            }else {
                JOptionPane.showMessageDialog(null, "Place not added");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddPlace.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAddPlaceMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       AddFurniture addfurniture =new AddFurniture();
       addfurniture.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked
    private void loadTable() throws SQLException, ClassNotFoundException{
        ArrayList<Object[]> rows=PlaceController.viewPlace();
        for(Object[] rowData:rows){
            dtm.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddPlace;
    private javax.swing.ButtonGroup btngroupAC;
    private javax.swing.JComboBox comboFurniture;
    private javax.swing.JComboBox comboMultimedia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JRadioButton radioBtnAC;
    private javax.swing.JRadioButton radioBtnNonAC;
    private javax.swing.JTable tableView;
    private javax.swing.JTextArea txtAdresss;
    private javax.swing.JTextField txtCrowd;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
