/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gateway.view.system;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import gateway.controllers.TeacherController;
import gateway.libraries.CurInstance;
import gateway.model.Teacher;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.CropImageFilter;
import java.awt.image.FilteredImageSource;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class AddTeacher extends javax.swing.JPanel {
    
    private int camAction = 0;
    Dimension dimension1 = WebcamResolution.QQVGA.getSize(); //java.awt.dimensions // //com.github.sarox.webcam.webCamResolution
    Webcam wCam = null;                            //com.github.sarox.webcam.webcam
    WebcamPanel webcamPanel = null;//com.github.sarox.webcam.webcampanel
    private int y = 1;
    private int takePhotoCheck = 1;
    /**
     * Creates new form AddTeacher
     */
    public AddTeacher() {
        initComponents();
        
        wCam = Webcam.getDefault();
        webcamPanel = new WebcamPanel(wCam, dimension1, false);
        loadWebCamPanel();
        
        labelMatch.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtSchoolAdrss = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        txtTP = new javax.swing.JTextField();
        txtSchoolName = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtAdress = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        labelMatch = new javax.swing.JLabel();
        labelStrength = new javax.swing.JLabel();
        btnAddClas = new javax.swing.JLabel();
        btnCancel = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        btnAdd = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        webCamDisplay = new javax.swing.JLabel();
        capIm = new javax.swing.JLabel();
        buttonOnCam = new javax.swing.JButton();

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setText("IdentificationPhoto");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 0, -1, -1));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Teacher ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 37, -1, -1));

        jLabel21.setText("Teacher Name");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 68, -1, -1));

        jLabel22.setText("Adress");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 103, -1, -1));

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 34, 210, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 65, 209, -1));

        txtSchoolAdrss.setColumns(20);
        txtSchoolAdrss.setRows(5);
        jScrollPane4.setViewportView(txtSchoolAdrss);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 200, -1));

        jLabel23.setText("Telephone No.");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        txtFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxActionPerformed(evt);
            }
        });
        jPanel1.add(txtFax, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 200, -1));

        jLabel24.setText("E-mail");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 200, -1));

        jLabel25.setText("Fax");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel26.setText("If School Teacher");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 84, 10));

        jLabel27.setText("School Name");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        txtTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTPActionPerformed(evt);
            }
        });
        jPanel1.add(txtTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 217, 210, -1));

        txtSchoolName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSchoolNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtSchoolName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 200, -1));

        jLabel28.setText("School Adress");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        txtAdress.setColumns(20);
        txtAdress.setRows(5);
        jScrollPane6.setViewportView(txtAdress);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 103, 209, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 484, 513));

        jPanel14.setOpaque(false);

        jLabel31.setText("Set Password");

        jLabel32.setText("Password");

        jLabel33.setText("Confirm Password");

        txtConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfirmPasswordKeyReleased(evt);
            }
        });

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel33)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addGap(35, 35, 35)))
                .addGap(47, 47, 47)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(txtConfirmPassword))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelStrength, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addGap(1, 1, 1)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(labelStrength, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel33))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 450, -1));

        btnAddClas.setText("Add Class");
        jPanel4.add(btnAddClas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 91, 43));

        btnCancel.setText("CANCEL");
        jPanel4.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, 91, 43));
        jPanel4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 338, 10));

        btnAdd.setText("Done");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        jPanel4.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 100, 50));

        webCamDisplay.setBackground(new java.awt.Color(51, 51, 51));
        webCamDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        webCamDisplay.setText("CAMERA");
        webCamDisplay.setOpaque(true);
        webCamDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webCamDisplayMouseClicked(evt);
            }
        });

        capIm.setBackground(new java.awt.Color(51, 51, 51));
        capIm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        capIm.setOpaque(true);

        buttonOnCam.setText("on camera");
        buttonOnCam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOnCamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(buttonOnCam))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(webCamDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(capIm, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(capIm, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(buttonOnCam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(webCamDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTPActionPerformed

    private void txtSchoolNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSchoolNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSchoolNameActionPerformed
    private void onCam() {
        if (camAction == 0) {
            webcamPanel.start();
            camAction = 1;
            buttonOnCam.setText("Off Camera");
        } else if (camAction == 1) {
            webcamPanel.stop();
            camAction = 0;
            buttonOnCam.setText("On Camera");

        }
    }
    private void webCamDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webCamDisplayMouseClicked
        takePic();
    }//GEN-LAST:event_webCamDisplayMouseClicked
      
    private void buttonOnCamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOnCamActionPerformed
        onCam();
    }//GEN-LAST:event_buttonOnCamActionPerformed
    private void loadWebCamPanel() {
        wCam.setViewSize(dimension1);
        webcamPanel.setFillArea(true);
        webCamDisplay.setLayout(new FlowLayout());//java.awt.flowlayout
        webCamDisplay.add(webcamPanel);
    }
    private void takePic() {

        if (y == 1) {
            if (wCam.isOpen()) {
                try {
                    takePhotoCheck = 1;
                    ImageIcon II = new ImageIcon(wCam.getImage());  //javax.swing.ImageIcon
                    Image image = II.getImage();   //javax.awt.Image
                    image = createImage(new FilteredImageSource(image.getSource(), new CropImageFilter(30, 0, 115, 144)));   //javax.awt.Image.cropimagefilter
                    capIm.setIcon(new ImageIcon(image));//javax.swing.ImageIcon

                    BufferedImage bufferedImage = new BufferedImage(image.getWidth(null), image.getHeight(null), BufferedImage.TYPE_INT_RGB); //java.awt.graphics
                    Graphics graphics = bufferedImage.createGraphics();  //java.awt.graphics
                    graphics.drawImage(image, 0, 0, null);
                    graphics.dispose();
                    String TeacherID = txtid.getText();
                    ImageIO.write(bufferedImage, "png", new File("./teacher/" + TeacherID + ".png"));             //java.io.file    
                    onCam();
                } catch (IOException ex) {                                                         //java.io.
                }
            } else {
            }
        }
    }
    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        if("".equals(txtName.getText())){
            JOptionPane.showConfirmDialog(null, "Name?", "name empty", JOptionPane.OK_CANCEL_OPTION);
            System.out.println("name");
        }else if("".equals(txtAdress.getText()) ){
            JOptionPane.showMessageDialog(null, "ADRESS not entered ");
        }else if("".equals(txtTP.getText()) ){
            JOptionPane.showMessageDialog(null, "TELEOPHONE NUMBER not entered ");
        }else if("matched".equals(labelMatch.getText())){
            JOptionPane.showConfirmDialog(null, "Is tyhis photo good for your Idfentity", "Confirm Identification Image", JOptionPane.YES_NO_OPTION);
            String id = txtid.getText();
            String date = CurInstance.Date();
            String name = txtName.getText();
            String photo= "./teacher/" +id+ ".png";
            String adress = txtAdress.getText();
            String  mobile = txtTP.getText();
            String school=txtSchoolName.getText();
             String schooladress= txtSchoolAdrss.getText();
            String password = txtPassword.getPassword().toString();
            String email = txtEmail.getText();
            String  fax = txtFax.getText();


            Teacher teacher =new Teacher(id,date,name,photo,adress,mobile,fax,email,school,schooladress,password);

            int res ;
            try {
                res = TeacherController.addTeacher(teacher);
                if(res>0){
                    JOptionPane.showMessageDialog(null, "Added Succesfully");
                }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(AddTeacher.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if("Mis-Match".equals(labelMatch.getText())||labelMatch.getText()==""){
            JOptionPane.showMessageDialog(null, "password ");
        } 

    }//GEN-LAST:event_btnAddMouseClicked
        
    private void txtConfirmPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmPasswordKeyReleased
        
        char[] password=txtPassword.getPassword();
        char[] confirmpassword =txtConfirmPassword.getPassword();
        String match="";
        if(confirmpassword.length <= password.length){
        for(int i=0;i<confirmpassword.length;i++){
            if(match==""||match=="matched"){
                if(password[i]==confirmpassword[i]){
                   match="matched";
//                    match="matched";
//                    labelMatch.setText(match);
                }else{
                    match="mis-match";
                    
                }
            }else{
                
            }
        }
//        if(password.length==confirmpassword.length){
//            labelMatch.setText(match);
//        }
        }else if(confirmpassword.length>password.length){
            match="longer than password";
        }
        if(confirmpassword.length==0){
                labelMatch.setText("");
        }else if(password.length==confirmpassword.length){
                labelMatch.setText(match);
        }else if(password.length>confirmpassword.length){
            if(match=="mis-match"){
                labelMatch.setText(match);
            }else{
                labelMatch.setText("");
            }
        }else if(password.length<confirmpassword.length){
                labelMatch.setText(match);
        }
//        System.out.println(password);
//        String confirmpassword=txtConfirmPassword.getPassword().toString();
//        System.out.println(confirmpassword);
        
    }//GEN-LAST:event_txtConfirmPasswordKeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
//        String password=txtPassword.getSelectedText() 
//                
//                look bellow
                
                // methanamama ganna one count elkanam nmka hadathki matma 
                //eth methan password eke akuruwalata ints letters adanguda kyala balnnannam aniwa me Strings split kranna ona 
                
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
       gateway.libraries.Validation.name(txtName);
    }//GEN-LAST:event_txtNameKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnAddClas;
    private javax.swing.JLabel btnCancel;
    private javax.swing.JButton buttonOnCam;
    private javax.swing.JLabel capIm;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel labelMatch;
    private javax.swing.JLabel labelStrength;
    private javax.swing.JTextArea txtAdress;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextArea txtSchoolAdrss;
    private javax.swing.JTextField txtSchoolName;
    private javax.swing.JTextField txtTP;
    private javax.swing.JTextField txtid;
    private javax.swing.JLabel webCamDisplay;
    // End of variables declaration//GEN-END:variables
}
