/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gateway.view.studentaccount;

import gateway.controllers.StudentController;
import gateway.view.home.Home;
import gateway.view.teacheraccount.TeacherAccounts;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class StudentAccount extends javax.swing.JPanel {

    private String id;
    private String name;
    private String grade;

    /**
     * Creates new form StudentAccount1
     */
    public StudentAccount(String id, String name) {
        System.out.println(id);
        System.out.println(id);
        initComponents();
        labelPhoto.setIcon(new ImageIcon("./student/" + id + ".png"));
        labelName.setText(name);
        this.id = id;
        this.name = name;
        
        System.out.println(id);
        
        
        try {
            this.grade = StudentController.getGradeOfStudent(id);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StudentAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelIssueCard = new javax.swing.JLabel();
        labelViewPayments = new javax.swing.JLabel();
        labelViewNewTute = new javax.swing.JLabel();
        labelIssueNewTute = new javax.swing.JLabel();
        labelviewattendancetoclass = new javax.swing.JLabel();
        labelChangeCourse = new javax.swing.JLabel();
        labelmarkattendance = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        labelNewCourse = new javax.swing.JLabel();
        studentAccountMainPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelPhoto = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tekton Pro Cond", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 204));
        jLabel3.setText("Tutes");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 330, 181, 25);

        jLabel5.setFont(new java.awt.Font("Tekton Pro Cond", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 204));
        jLabel5.setText("Attendance");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, 40, 181, 25);

        jLabel6.setFont(new java.awt.Font("Tekton Pro Cond", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 204));
        jLabel6.setText("Payments");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 130, 181, 25);

        jLabel7.setFont(new java.awt.Font("Tekton Pro Cond", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 204));
        jLabel7.setText("Classes");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 230, 181, 25);

        labelIssueCard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelIssueCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gateway/view/images/student/ISSUECARD.png"))); // NOI18N
        labelIssueCard.setText("     This Month's");
        labelIssueCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelIssueCardMouseClicked(evt);
            }
        });
        jPanel3.add(labelIssueCard);
        labelIssueCard.setBounds(0, 160, 220, 20);

        labelViewPayments.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelViewPayments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gateway/view/images/student/viewpayments.png"))); // NOI18N
        labelViewPayments.setText("      View Previous Month's");
        labelViewPayments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelViewPaymentsMouseClicked(evt);
            }
        });
        jPanel3.add(labelViewPayments);
        labelViewPayments.setBounds(0, 180, 210, 20);

        labelViewNewTute.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelViewNewTute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gateway/view/images/student/viewtuteset.png"))); // NOI18N
        labelViewNewTute.setText("     See Tute Collection");
        labelViewNewTute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelViewNewTuteMouseClicked(evt);
            }
        });
        jPanel3.add(labelViewNewTute);
        labelViewNewTute.setBounds(0, 380, 210, 20);

        labelIssueNewTute.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelIssueNewTute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gateway/view/images/student/newtute.png"))); // NOI18N
        labelIssueNewTute.setText("      Mark new Tute ");
        labelIssueNewTute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelIssueNewTuteMouseClicked(evt);
            }
        });
        jPanel3.add(labelIssueNewTute);
        labelIssueNewTute.setBounds(0, 360, 220, 20);

        labelviewattendancetoclass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelviewattendancetoclass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gateway/view/images/student/viewattendace.png"))); // NOI18N
        labelviewattendancetoclass.setText("      View Attendance to Classes");
        labelviewattendancetoclass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelviewattendancetoclassMouseClicked(evt);
            }
        });
        jPanel3.add(labelviewattendancetoclass);
        labelviewattendancetoclass.setBounds(0, 80, 220, 20);

        labelChangeCourse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelChangeCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gateway/view/images/student/ChangeClass.png"))); // NOI18N
        labelChangeCourse.setText("     Change Permanent Class");
        labelChangeCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelChangeCourseMouseClicked(evt);
            }
        });
        jPanel3.add(labelChangeCourse);
        labelChangeCourse.setBounds(0, 280, 210, 20);

        labelmarkattendance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelmarkattendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gateway/view/images/student/markattendance.png"))); // NOI18N
        labelmarkattendance.setText("     Mark Attendance");
        labelmarkattendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelmarkattendanceMouseClicked(evt);
            }
        });
        jPanel3.add(labelmarkattendance);
        labelmarkattendance.setBounds(0, 60, 210, 20);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gateway/view/images/student/newcourse.png"))); // NOI18N
        jButton3.setText("jButton3");
        jButton3.setContentAreaFilled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(0, 100, 210, 30);

        labelNewCourse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNewCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gateway/view/images/student/newcourse.png"))); // NOI18N
        labelNewCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelNewCourseMouseClicked(evt);
            }
        });
        jPanel3.add(labelNewCourse);
        labelNewCourse.setBounds(0, 260, 210, 20);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 450));

        studentAccountMainPanel.setOpaque(false);

        javax.swing.GroupLayout studentAccountMainPanelLayout = new javax.swing.GroupLayout(studentAccountMainPanel);
        studentAccountMainPanel.setLayout(studentAccountMainPanelLayout);
        studentAccountMainPanelLayout.setHorizontalGroup(
            studentAccountMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        studentAccountMainPanelLayout.setVerticalGroup(
            studentAccountMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jPanel1.add(studentAccountMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 870, 340));

        jButton1.setText("teacher accounts");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, -1, 30));

        jButton2.setText("exit system");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 120, 30));

        jLabel9.setText("LOG OUT ");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 90, 80));

        jLabel2.setText("Pay Month ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 360, 70));

        jLabel4.setText("Mark Attendance");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 370, 70));
        jPanel1.add(labelPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 140, 140));
        jPanel1.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 460, 40));

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gateway/view/images/student/student small. 07.19.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelIssueCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIssueCardMouseClicked
       
    }//GEN-LAST:event_labelIssueCardMouseClicked

    private void labelViewPaymentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelViewPaymentsMouseClicked
        studentAccountMainPanel.removeAll();
        ViewAttendance p1 = new ViewAttendance();
        p1.setSize(studentAccountMainPanel.getSize());
        studentAccountMainPanel.repaint();
        studentAccountMainPanel.revalidate();
        studentAccountMainPanel.add(p1);
    }//GEN-LAST:event_labelViewPaymentsMouseClicked

    private void labelViewNewTuteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelViewNewTuteMouseClicked
        studentAccountMainPanel.removeAll();
        TuteCollection p1 = new TuteCollection(id);
        p1.setSize(studentAccountMainPanel.getSize());
        studentAccountMainPanel.repaint();
        studentAccountMainPanel.revalidate();
        studentAccountMainPanel.add(p1);
    }//GEN-LAST:event_labelViewNewTuteMouseClicked

    private void labelIssueNewTuteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIssueNewTuteMouseClicked
        studentAccountMainPanel.removeAll();
        Ticktute p1 = new Ticktute(id);
        p1.setSize(studentAccountMainPanel.getSize());
        studentAccountMainPanel.repaint();
        studentAccountMainPanel.revalidate();
        studentAccountMainPanel.add(p1);
    }//GEN-LAST:event_labelIssueNewTuteMouseClicked

    private void labelviewattendancetoclassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelviewattendancetoclassMouseClicked
        studentAccountMainPanel.removeAll();
        ViewAttendance p1 = new ViewAttendance();
        p1.setSize(studentAccountMainPanel.getSize());
        studentAccountMainPanel.repaint();
        studentAccountMainPanel.revalidate();
        studentAccountMainPanel.add(p1);
    }//GEN-LAST:event_labelviewattendancetoclassMouseClicked

    private void labelChangeCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelChangeCourseMouseClicked
        studentAccountMainPanel.removeAll();
        ChangePermanentClass p1 = new ChangePermanentClass();
        p1.setSize(studentAccountMainPanel.getSize());
        studentAccountMainPanel.repaint();
        studentAccountMainPanel.revalidate();
        studentAccountMainPanel.add(p1);
    }//GEN-LAST:event_labelChangeCourseMouseClicked

    private void labelmarkattendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelmarkattendanceMouseClicked
        
    }//GEN-LAST:event_labelmarkattendanceMouseClicked

    private void labelNewCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNewCourseMouseClicked
        studentAccountMainPanel.removeAll();
        RegisterToNew p1 = new RegisterToNew(grade,id);
        p1.setSize(studentAccountMainPanel.getSize());
        studentAccountMainPanel.repaint();
        studentAccountMainPanel.revalidate();
        studentAccountMainPanel.add(p1);
        
    }//GEN-LAST:event_labelNewCourseMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Home.getHomePage().loadMainPanel();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
//        studentAccountMainPanel.removeAll();
//        RegisterToNew p1 = new RegisterToNew();
//        p1.setSize(studentAccountMainPanel.getSize());
//        studentAccountMainPanel.repaint();
//        studentAccountMainPanel.revalidate();
//        studentAccountMainPanel.add(p1);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelChangeCourse;
    private javax.swing.JLabel labelIssueCard;
    private javax.swing.JLabel labelIssueNewTute;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNewCourse;
    private javax.swing.JLabel labelPhoto;
    private javax.swing.JLabel labelViewNewTute;
    private javax.swing.JLabel labelViewPayments;
    private javax.swing.JLabel labelmarkattendance;
    private javax.swing.JLabel labelviewattendancetoclass;
    private javax.swing.JPanel studentAccountMainPanel;
    // End of variables declaration//GEN-END:variables
}
